development:
  clients:
    default:
      database: microblog_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: microblog_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

# mongoid 5.x
#
production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGOLAB_URI'] %>.
     uri: mongodb://heroku_z0jrsmxr:katih29pmo7nvet2esc881pt6o@ds053944.mongolab.com:53944/heroku_z0jrsmxr

     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15
